export { default as Layout } from './Layout'
export { default as HeadMeta } from './HeadMeta'
export { default as Footer } from './Footer'
export { default as NavBar } from './Navbar'
export { default as GlobalStyles } from './GlobalStyles'
export * from './UIkit'
